#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import division,print_function
""" Start the toyz web server """

print('Loading dependencies, please wait...')
from toyz.web.app import init_web_app

init_web_app()